local function theme_setup()
    local p = {
        lightred = "#e85f5f",
        dullgreen = "#8ee6b4",
        lightyellow = "#e5c76b",
        lightblue = "#8ecae6",
        purple = "#bdb2ff",
        lightgreen = "#9dd274",
        lightgrey = "#b3b9b8",
        darkgrey = "#2d3437",
        brightred = "#e63946",
        brightgreen = "#77e0bf",
        brightyellow = "#fec89a",
        darkblue = "#7798E0",
        orange = "#f39660",

        comment = "#404749",
        black = "#000000",

        grey = "#404040",

        bg = "#0e0e0e",
        bg1 = "#202020",
        bg2 = "#141414",
        bg3 = "#181818",
        bg4 = "#1e1e1e",
        bg5 = "#121212",

        foreground = "#dadada",
        none = "NONE",
    }


    local highlights = {
        -- Base highlights
        Boolean = { fg = p.purple },
        Character = { fg = p.brightgreen },
        ColorColumn = { bg = p.none },
        Comment = { fg = p.comment, style = { italic = true } },
        Conceal = { fg = p.lightblue, bg = p.bg },
        Conditional = { fg = p.lightgreen },
        Constant = { fg = p.purple },
        Cursor = { fg = p.foreground, bg = p.foreground },
        CurSearch = { link = "IncSearch" },
        CursorColumn = { bg = p.bg },
        CursorIM = { fg = p.foreground, bg = p.foreground },
        CursorLine = { bg = p.bg3 },
        CursorLineNr = { fg = p.foreground },
        Debug = { fg = p.lightred },
        Define = { fg = p.lightgreen },
        Delimiter = { fg = p.foreground },
        DiffAdd = { fg = p.lightblue, bg = p.bg },
        DiffChange = { fg = p.purple, bg = p.bg },
        DiffDelete = { fg = p.lightred, bg = p.bg },
        DiffText = { fg = p.lightred, bg = p.bg },
        Directory = { fg = p.lightblue },
        EndOfBuffer = { fg = p.bg },
        Error = { fg = p.lightred, bg = p.bg },
        ErrorMsg = { fg = p.lightred, bg = p.bg },
        Exception = { fg = p.lightgreen },
        Float = { fg = p.purple },
        FloatBorder = { fg = p.lightgrey },
        FoldColumn = { fg = p.lightblue, bg = p.bg },
        Folded = { fg = p.grey, bg = p.bg2 },
        Function = { fg = p.lightgreen },
        Identifier = { fg = p.purple },
        Ignore = { fg = p.lightgrey, bg = p.bg },
        IncSearch = { fg = p.black, bg = p.lightgreen },
        Include = { fg = p.lightgreen },
        Keyword = { fg = p.lightgreen, style = { italic = true } },
        Label = { fg = p.lightblue },
        LineNr = { fg = p.darkgrey },
        Macro = { fg = p.lightgreen },
        MatchParen = { fg = p.lightblue, bg = p.bg },
        ModeMsg = { fg = p.foreground, bg = p.bg },
        MoreMsg = { fg = p.purple },
        MsgArea = { fg = p.foreground, bg = p.bg },
        MsgSeparator = { fg = p.foreground, bg = p.bg },
        NonText = { fg = p.lightred },
        Normal = { fg = p.foreground, bg = p.bg },
        NormalFloat = { bg = p.bg3 },
        NormalNC = { fg = p.foreground, bg = p.bg },
        Number = { fg = p.lightyellow },
        Operator = { fg = p.lightgreen },
        Pmenu = { bg = p.bg3 },
        PmenuSbar = { bg = p.bg4 },
        PmenuSel = { fg = p.black, bg = p.lightblue },
        PmenuThumb = { bg = p.bg1 },
        PreCondit = { fg = p.lightgreen },
        PreProc = { fg = p.lightgreen },
        Question = { fg = p.purple },
        QuickFixLine = { bg = p.dullgreen },
        Repeat = { fg = p.lightgreen },
        Search = { fg = p.black, bg = p.lightblue },
        SignColumn = { fg = p.bg, bg = p.bg },
        Special = { fg = p.lightgreen },
        SpecialChar = { fg = p.foreground },
        SpecialComment = { fg = p.dullgreen },
        SpecialKey = { fg = p.lightblue },
        SpellBad = { fg = p.dullgreen },
        SpellCap = { fg = p.lightgreen },
        SpellLocal = { fg = p.lightblue },
        SpellRare = { fg = p.lightgreen },
        Statement = { fg = p.lightgreen },
        StatusLine = { fg = p.dullgreen, bg = p.bg },
        StatusLineNC = { bg = p.dullgreen, fg = p.bg },
        Storage = { fg = p.brightred },
        StorageClass = { fg = p.lightgrey },
        String = { fg = p.orange },
        Structure = { fg = p.lightgreen },
        Substitute = { fg = p.black, bg = p.brightred },
        TabLine = { fg = p.dullgreen, bg = p.bg },
        TabLineSelCount = { fg = p.dullgreen, bg = p.bg },
        TabLineInactiveCount = { fg = p.dullgreen, bg = p.bg1 },
        TabLineFill = { fg = p.foreground, bg = p.bg4 },
        TabLineSel = { fg = p.foreground, bg = p.bg },
        TabLineInactive = { fg = p.grey, bg = p.bg1 },
        Tag = { fg = p.lightblue },
        TermCursor = { fg = p.foreground, bg = p.foreground },
        TermCursorNC = { fg = p.foreground, bg = p.foreground },
        Title = { fg = p.lightblue, bold = true },
        Todo = { fg = p.lightred, bg = p.bg },
        Type = { fg = p.purple },
        Typedef = { fg = p.lightgreen },
        Underlined = { fg = p.dullgreen, underline = true },
        Variable = { fg = p.purple },
        VertSplit = { fg = p.darkgrey },
        Visual = { bg = p.bg3 },
        VisualNOS = { bg = p.bg },
        WarningMsg = { fg = p.lightyellow, bg = p.bg },
        Whitespace = { fg = p.grey },
        WildMenu = { fg = p.lightgrey, bg = p.lightblue },
        lCursor = { fg = p.foreground, bg = p.foreground },

        -- Diagnostic
        DiagnosticError = { fg = p.lightred },
        DiagnosticHint = { fg = p.dullgreen },
        DiagnosticInfo = { fg = p.lightblue },
        DiagnosticWarn = { fg = p.lightyellow },
        DiagnosticUnnecessary = { fg = p.none },

        -- diff
        diffAdded = { fg = p.lightblue },
        diffChanged = { fg = p.purple },
        diffFile = { fg = p.lightgrey },
        diffIndexLine = { fg = p.lightgreen },
        diffLine = { fg = p.lightred },
        diffNewFile = { fg = p.purple },
        diffOldFile = { fg = p.purple },
        diffRemoved = { fg = p.lightred },

        -- LSP
        LspInfoFiletype = { fg = p.orange },
        LspReferenceText = { bg = p.lightgrey },
        LspReferenceRead = { bg = p.lightgrey },
        LspReferenceWrite = { bg = p.lightgrey },
        LspInfoBorder = { link = "FloatBorder" },

        -- Neovim
        healthError = { fg = p.lightred },
        healthSuccess = { fg = p.lightblue },
        healthWarning = { fg = p.purple },

        -- nvim-cmp: https://github.com/hrsh7th/nvim-cmp
        CmpDocumentationBorder = { fg = p.lightgrey, bg = p.bg },
        CmpItemAbbr = { fg = p.foreground, bg = p.bg3 },
        CmpItemAbbrDeprecated = { fg = p.dullgreen, bg = p.bg3 },
        CmpItemAbbrMatch = { fg = p.orange, bg = p.bg3 },
        CmpItemAbbrMatchFuzzy = { fg = p.orange, bg = p.bg3 },
        CmpItemKind = { fg = p.lightblue, bg = p.bg3 },
        CmpItemMenu = { fg = p.dullgreen, bg = p.bg3 },
        CmpItemKindFolder = { fg = p.lightblue },
        CmpItemKindFile = { fg = p.dullgreen },
        CmpItemKindConstructor = { fg = p.purple },
        CmpItemKindInterface = { fg = p.purple },
        CmpItemKindReference = { fg = p.purple },
        CmpItemKindConstant = { fg = p.purple },
        CmpItemKindProperty = { fg = p.purple },
        CmpItemKindModule = { fg = p.purple },
        CmpItemKindClass = { fg = p.purple },
        CmpItemKindField = { fg = p.purple },
        CmpItemKindEvent = { fg = p.purple },
        CmpItemKindSnippet = { fg = p.lightblue },
        CmpItemKindKeyword = { fg = p.lightblue },
        CmpItemKindValue = { fg = p.lightblue },
        CmpItemKindOperator = { fg = p.lightblue },
        CmpItemKindTypeParameter = { fg = p.lightgrey },
        CmpItemKindVariable = { fg = p.lightgrey },
        CmpItemKindText = { fg = p.lightgrey },
        CmpItemKindUnit = { fg = p.lightgrey },

        -- Yank
        YankHighlight = { bg = p.bg3 },

        -- Markdown
        markdownCodeBlock = { fg = p.lightgrey },
        markdownCodeDelimeter = { fg = p.lightgrey },
        markdownUrl = { fg = p.orange },
        markdownLink = { fg = p.foreground, underline = true },

        -- nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter
        ["@attribute"] = { fg = p.lightblue },
        ["@boolean"] = { fg = p.lightgreen },
        ["@character"] = { fg = p.lightblue },
        ["@comment"] = { fg = p.comment, style = { italic = true } },
        ["@conditional"] = { fg = p.lightred },
        ["@constant"] = { fg = p.lightgreen },
        ["@constant.builtin"] = { fg = p.brightgreen },
        ["@constant.macro"] = { fg = p.lightyellow },
        ["@constructor"] = { fg = p.lightgreen },
        ["@exception"] = { fg = p.lightred },
        ["@field"] = { fg = p.lightred },
        ["@float"] = { link = "@number" },
        ["@function"] = { fg = p.lightgreen },
        ["@function.builtin"] = { fg = p.lightgreen },
        ["@function.macro"] = { fg = p.lightgreen },
        ["@include"] = { fg = p.darkblue },
        ["@keyword"] = { fg = p.darkblue, style = { italic = true } },
        ["@keyword.function"] = { fg = p.darkblue, style = { italic = true } },
        ["@keyword.operator"] = { fg = p.darkblue, style = { italic = true } },
        ["@keyword.return"] = { fg = p.darkblue, style = { italic = true } },
        ["@label"] = { fg = p.brightgreen },
        ["@method"] = { fg = p.lightgreen },
        ["@namespace"] = { fg = p.brightyellow },
        ["@number"] = { fg = p.orange },
        ["@operator"] = { fg = p.lightyellow },
        ["@parameter"] = { fg = p.lightred },
        ["@parameter.reference"] = { fg = p.brightred },
        ["@property"] = { fg = p.dullgreen },
        ["@punctuation.bracket"] = { fg = p.lightgrey },
        ["@punctuation.delimiter"] = { fg = p.lightgrey },
        ["@punctuation.special"] = { fg = p.lightgrey },
        ["@repeat"] = { fg = p.brightyellow },
        ["@string"] = { fg = p.orange },
        ["@string.escape"] = { fg = p.lightblue },
        ["@string.regex"] = { fg = p.orange },
        ["@string.special"] = { fg = p.lightblue },
        ["@symbol"] = { fg = p.lightred },
        ["@tag"] = { fg = p.lightblue },
        ["@tag.attribute"] = { fg = p.lightred },
        ["@tag.delimiter"] = { fg = p.lightgrey },
        ["@text"] = { fg = p.lightgrey },
        ["@text.danger"] = { fg = p.darkgrey },
        ["@text.emphasis"] = { fg = p.lightgrey, italic = true },
        ["@text.environment.name"] = { fg = p.lightyellow },
        ["@text.environtment"] = { fg = p.purple },
        ["@text.literal"] = { fg = p.dullgreen, italic = true },
        ["@text.math"] = { fg = p.lightgreen },
        ["@text.note"] = { fg = p.black, bg = p.dullgreen },
        ["@text.reference"] = { fg = p.lightgreen },
        ["@text.strike"] = { fg = p.lightgrey, strikethrough = true },
        ["@text.strong"] = { fg = p.lightgrey, bold = true },
        ["@text.title"] = { fg = p.lightyellow, bold = true },
        ["@text.underline"] = { fg = p.purple, underline = true },
        ["@text.uri"] = { fg = p.lightyellow, underline = true },
        ["@text.warning"] = { fg = p.darkgrey, bg = p.lightred },
        ["@type"] = { fg = p.lightblue, style = { italic = true } },
        ["@type.builtin"] = { fg = p.lightblue, style = { italic = true }},
        ["@storageclass"] = { link = "@keyword" },
        ["@type.qualifier"] = { link = "@keyword" },
        ["@variable"] = { fg = p.foreground },
        ["@variable.builtin"] = { link = "@keyword" },

        -- LSP semantic tokens
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.interface"] = { link = "Identifier" },
        ["@lsp.type.keyword"] = { link = "@keyword" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.variable"] = { link = "@variable" }, -- use treesitter styles for regular variables
        ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
        ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
        ["@lsp.typemod.operator.injected"] = { link = "@operator" },
        ["@lsp.typemod.string.injected"] = { link = "@string" },
        ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
        ["@lsp.typemod.variable.injected"] = { link = "@variable" },

        -- telescope.nvim: https://github.com/nvim-telescope/telescope.nvim
        TelescopeMatching = { fg = p.dullgreen },
        TelescopeSelection = { fg = p.dullgreen, bg = p.bg4 },
        TelescopeMultiSelection = { bg = p.lightred },
        TelescopePromptTitle = { fg = p.bg, bg = p.orange },
        TelescopePreviewLine = { bg = p.bg },
        TelescopePromptPrefix = { fg = p.orange, bg = p.bg4 },
        TelescopePromptBorder = { fg = p.bg4, bg = p.bg4 },
        TelescopePromptNormal = { fg = p.fg, bg = p.bg4 },
        TelescopeResultsTitle = { fg = p.bg, bg = p.lightred },
        TelescopeResultsBorder = { fg = p.bg3, bg = p.bg3 },
        TelescopeResultsNormal = { fg = p.foreground, bg = p.bg3 },
        TelescopePreviewTitle = { fg = p.bg, bg = p.darkblue },
        TelescopePreviewBorder = { fg = p.bg5, bg = p.bg5 },
        TelescopePreviewNormal = { fg = p.foreground, bg = p.bg5 },
    }

    -- Set the highlights
    for group, colors in pairs(highlights) do
        if colors.style then
            if type(colors.style) == "table" then
                colors = vim.tbl_extend("force", colors, colors.style)
            end
            colors.style = nil
        end
        vim.api.nvim_set_hl(0, group, colors)
    end
end

theme_setup()
