#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
polybar -q bar &
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          32

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a spotify-launcher desktop='^3' state=tile follow=on
bspc rule -a Zathura state=tiled 

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"
bspc config focused_border_color "#327bd1"
