local cmd = vim.cmd -- execute Vim commands
-- cmd("let ayucolor=\"dark\"")
cmd("set termguicolors")
cmd('colorscheme tender')
cmd("highlight Directory gui=bold guifg=#677FA3")
cmd("highlight NvimTreeOpenedFolderName gui=bold")
cmd("highlight Normal guibg=#0f0f0f")
cmd('highlight clear SignColumn')
cmd('highlight clear LineNr')
-- cmd('highlight GitGutterAdd guibg=#0f0f0f guifg=#009900')
-- cmd('highlight GitGutterChange guibg=#0f0f0f guifg=#bbbb00')
-- cmd('highlight GitGutterDelete guibg=#0f0f0f guifg=#ff2222')
-- cmd('highlight GruvboxRedSign ctermfg=167 ctermbg=237 guifg=#fb4934 guibg=#0f0f0f')
-- cmd('highlight GruvboxYellowSign ctermfg=214 ctermbg=237 guifg=#fabd2f guibg=#0f0f0f')
-- cmd('highlight GruvboxBlueSign ctermfg=109 ctermbg=237 guifg=#83a598 guibg=#0f0f0f')
-- cmd('highlight GruvboxAquaSign ctermfg=108 ctermbg=237 guifg=#8ec07c guibg=#0f0f0f')
-- cmd('highlight GruvboxBg3 ctermfg=108 guibg=#0f0f0f guifg=#0f0f0f')
cmd('highlight VertSplit ctermfg=241 ctermbg=235 guibg=#0f0f0f guifg=#0f0f0f')
cmd('highlight EndOfBuffer ctermfg=241 guifg=#0f0f0f')
cmd('highlight BufferCurrent guibg=#0f0f0f')
cmd('highlight BufferCurrentIndex guibg=#0f0f0f')
cmd('highlight BufferCurrentMod guibg=#0f0f0f')
cmd('highlight BufferCurrentSign guibg=#0f0f0f')
cmd('highlight BufferCurrentIcon guibg=#0f0f0f')
cmd('highlight BufferCurrentMod guibg=#0f0f0f')
cmd('highlight BufferOffset guibg=#0f0f0f')
cmd('highlight StatusLine guifg=#0f0f0f guibg=#0f0f0f')
cmd('highlight StatusLineNC guibg=#0f0f0f')
cmd('highlight TabLineFill guibg=#0f0f0f')
cmd('highlight TabLineSel guibg=#0f0f0f')
